<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpiryDate_input</name>
   <tag></tag>
   <elementGuidId>10ef3d9f-1fdf-41cd-8906-d6ee6da37380</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_txtExpiryDate_dateInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_txtExpiryDate_dateInput&quot;]</value>
   </webElementProperties>
</WebElementEntity>
