<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CarrierCustCodeC_input</name>
   <tag></tag>
   <elementGuidId>a45f1d48-28ec-49e1-b9d1-c67235110160</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustomerCodePrePaid-list&quot;]/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustomerCodePrePaid-list&quot;]/span/input</value>
   </webElementProperties>
</WebElementEntity>
