<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_email format</name>
   <tag></tag>
   <elementGuidId>97778c33-27ce-457d-8e1e-a65057921c88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-home/main/app-create-airline/form/div[2]/mat-form-field[2]/div/div[2]/div/mat-error/app-error/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-home/main/app-create-airline/form/div[2]/mat-form-field[2]/div/div[2]/div/mat-error/app-error/span</value>
   </webElementProperties>
</WebElementEntity>
