<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Origin_input-found</name>
   <tag></tag>
   <elementGuidId>dcb8509d-2747-41f7-8cc9-6dbc00dfd12e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbOrigin_DropDown&quot;]/div[2]/ul/li/table/tbody/tr/td[1][count(. | //*[(text() = 'SIN' or . = 'SIN')]) = count(//*[(text() = 'SIN' or . = 'SIN')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbOrigin_DropDown&quot;]/div[2]/ul/li/table/tbody/tr/td[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SIN</value>
   </webElementProperties>
</WebElementEntity>
