<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cube-navigator</name>
   <tag></tag>
   <elementGuidId>db729261-92d7-4a50-9d73-05baf30b8b07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//cube-navigator</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>cube-navigator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apps</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-version</name>
      <type>Main</type>
      <value>11.0.9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/app-home[@class=&quot;ng-star-inserted&quot;]/app-header[1]/mat-toolbar[@class=&quot;mat-toolbar mat-primary mat-toolbar-multiple-rows&quot;]/mat-toolbar-row[@class=&quot;mat-toolbar-row mat-elevation-z2 p-0 header&quot;]/nav[@class=&quot;ml-auto ng-star-inserted&quot;]/div[@class=&quot;d-inline-block mr-0&quot;]/cube-navigator[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cube-navigator</value>
   </webElementXpaths>
</WebElementEntity>
