<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Registration_Success</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>e82c5331-4254-4ba4-9e18-c1df7544ba0d</testSuiteGuid>
   <testCaseLink>
      <guid>f9df7a61-ba56-4820-9eaf-dc5aea5d3e1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 1/Registration Process/0 Registration Success</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>519fa998-e042-43a1-873a-151a8e48b49f</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-1</value>
         </iterationEntity>
         <testDataId>Data Files/Registration/TestData_Registration</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>234d982d-a407-4fac-9709-bbc6a278bd55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>621f85aa-de18-4937-befd-a3d760a89d41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b67657f-d0a3-4f15-8d77-8dcf7e5c116e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bce914a4-c8ae-44be-b103-5bea871f57a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>243a38e5-86f5-4201-a51c-5130da47b856</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2ba8d98d-c20e-44a0-a320-5bffcc2f35d1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ae246358-1c39-4945-859c-ebd9f5e1a39a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 1/Registration Process/1 Registration Failed - Check Field</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>db62ab46-fa5d-41ab-88b7-6c703cf0953b</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/Registration/TestData_Registration</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>886654c1-972f-415c-bfb5-c677030c90df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94ed3081-a56a-4449-86f1-5fdfa820fd7f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc114985-df77-4a22-b616-7b091c01ba98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd2eba8b-4c15-4072-b633-0446f6a0bce4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>069d6c15-71f7-4026-82b6-2111d8998cd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e3eef9e-db7a-4004-9a12-68cd4ea7e579</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a771ade-7b4a-4091-88e6-d8736a9278bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 1/Registration Process/2 Registration Failed - Email Existed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>396b5119-5930-45c1-92eb-b80ecea6946b</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-3</value>
         </iterationEntity>
         <testDataId>Data Files/Registration/TestData_Registration</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55728103-3779-4dca-9189-4fe48b3c9a04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c2fe59b-0d48-4cb3-b316-bd34235f8714</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e57dad3-717b-47f5-af11-6ab16b871981</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aa5d7dd-f1d8-4bc4-8185-be11a115af86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc04242-70ee-4cb6-b005-dee6d9a7f08e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac7ed043-b017-4073-8108-88be747ae73c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
