<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_Registration_Error_emailexisted</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>434a47b5-26f4-4b82-b72c-d92fd02c69ab</testSuiteGuid>
   <testCaseLink>
      <guid>e9592258-b367-4ea3-b4b3-188cf919d0d7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 1/Registration Process/1 Registration Failed - Email Existed</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>54e39ff0-16ad-4e10-8618-b9b1191c6f3c</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>3-3</value>
         </iterationEntity>
         <testDataId>Data Files/Sprint_1/TD_Registration</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>55728103-3779-4dca-9189-4fe48b3c9a04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c2fe59b-0d48-4cb3-b316-bd34235f8714</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e57dad3-717b-47f5-af11-6ab16b871981</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3aa5d7dd-f1d8-4bc4-8185-be11a115af86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffc04242-70ee-4cb6-b005-dee6d9a7f08e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac7ed043-b017-4073-8108-88be747ae73c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
