<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WeightUOM_input</name>
   <tag></tag>
   <elementGuidId>e9fed326-d46b-462e-8c56-6643b0e625fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbWeightUOM_Input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbWeightUOM_Input&quot;]</value>
   </webElementProperties>
</WebElementEntity>
