<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Success</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c7d7acb3-1ab3-4d00-b9ba-1d35ca9bb87e</testSuiteGuid>
   <testCaseLink>
      <guid>8b33d4c0-32fd-4755-84ea-b89bd793778f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication Login/Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bf7ae97e-b896-44ab-b4d5-761e2b00b3f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 2/Login to Booking Concierge/0 Login Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2020a495-7060-4f34-b7e9-4f3017b45cf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b99673a-7f6b-4e9b-ae57-42b8ef9938e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2f81cf4-86e9-45b9-9b5e-81b20e6793e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 9/Same AWB Booking Request Created and Sent by More than One BC User/0 Sent Booking Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a725ba06-c46f-4cc3-b39a-e4aaf1585eb3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f3b2ff6-d579-4bc5-acce-049b64d3dd72</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7b4577e-a4ba-4c4f-8f63-3e08aa754c4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>be5f18d8-9f13-4584-932f-a5cf03f1a7d3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2840dd69-5f64-45aa-8459-3023cc285833</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0efbf665-bd81-42f3-8607-a4b6f48d9619</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>96da2afd-b9d6-4020-83f9-33c37844e30d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b8e3a9-ab3c-41fb-8f2c-e479a5f06349</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b763e98-c93e-4417-b20f-82c7bf977156</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b13ef0a3-1de0-45e6-8191-44b6f5bbc72d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>51d113f4-1d21-49a7-9813-8d5a1fbef2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>716d3dd4-0df1-4a3b-90b5-6e2a5a0cc74d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>70200a67-f36d-4e32-afd5-10b7ab890a91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d64b050-fb8f-4b93-8fa3-d7c19ddd2673</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75bd6afa-8931-4691-8eb7-c92e3d7837a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cec22d-ef78-44ad-abec-1f33da164cb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dbe6385-60d7-4cdc-92d7-af58aec6f5a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbe09626-b648-4fd8-974c-f6feed055e4d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ba22430-a1b9-4d0c-8771-cf39d404a6b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49ab2686-be73-4157-9d1b-2b75256d9b2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0839d313-5c74-4496-b833-d005d35edfeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1af9e34e-7291-4d80-80d5-49bde95e3ae1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef24546b-96e9-44bf-96ec-2f64cb4d2338</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c453623-16e5-41a6-beaa-dd55e18add9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e3f9158c-fea7-4df9-8eb5-15d1c29061ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 9/Same AWB Booking Request Created and Sent by More than One BC User/1 Login 2nd User</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09c5be1d-7b5e-4fbd-8ec9-d143e5932e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf5c2633-56b4-4702-a0ec-97493e3825c9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ccccb007-171b-4d24-a374-61d048867a12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 9/Same AWB Booking Request Created and Sent by More than One BC User/2 Sent 2nd Booking Request</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07206930-0907-45f2-b3b4-9a7a23558483</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9416cd41-e1ad-433e-bed3-150bef65608b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a972e11-c825-4b66-9ef8-482f29aa2907</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5634ee9c-da36-480b-bda2-c8a32ce7f87a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58dfeb27-3ab0-4d96-9848-c9e300708191</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5f5b820c-bf75-468e-bbbd-299e69fb75a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5a7619f8-f51e-42f4-a498-cc04814d87e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>90a0a542-2171-46cc-9e37-f4289bfd0066</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>611e9046-ea0f-4ef3-93ee-8743dfe94908</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c6bffdf-5c13-42a4-b523-dc75d26c3d54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8c26822-4dfb-48d0-87aa-f0e889ab7f03</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>150a5c07-9dfa-4124-9766-f6925b9d099e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>424cb11c-54a6-4865-8b70-20a6876b7761</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7c83d9b8-43e2-425b-8019-b7dbe85f654f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123693f1-5582-453e-b041-0e40e538e4fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3486b1f8-f096-4da7-a3cb-cab3c03cd996</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f72a4bf1-9547-4ca1-a485-74041ee152db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2527cc71-9037-4e08-a263-020008efe888</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aabd9b42-27a3-4091-a4ac-9f12a5125c7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a83c9b5-43cd-4bed-b312-8e9d55f603ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33c4549f-ec5a-467f-b60c-015d7d74d15f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>07b0ff32-41e2-4c80-8974-c0360daa7e95</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd99bd0d-72c4-4ab1-9907-10af8746c3af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cdc4fe15-5d41-487f-8a94-da8a3bea9c5e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58802fe5-d815-4619-8937-bebe4d353c17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 9/Open New Tab</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f273ac8-a58e-42eb-b31f-1f0e44b74710</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>50ce7941-e06e-4752-bf74-d1696c3a299d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/BC1/Sprint 9/Same AWB Booking Request Created and Sent by More than One BC User/3 Go to Emails Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad95689b-cee0-4379-ba2c-2354220cd5e4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eec3ee9d-2102-4946-b2a6-2444c8319112</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
