<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_Company Code</name>
   <tag></tag>
   <elementGuidId>d104111d-00f8-464c-9125-ac997d8e9e0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_MainContent_gvCompanyManagement_ctl00_ctl02_ctl02_Filter_TemplateColumn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[3]/table/tbody/tr/td[2]/div[7]/div/table/thead/tr[2]/td[2]/input[2]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$MainContent$gvCompanyManagement$ctl00$ctl02$ctl02$Filter_TemplateColumn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>$find(&quot;ctl00_MainContent_gvCompanyManagement&quot;)._showFilterMenu(&quot;ctl00_MainContent_gvCompanyManagement_ctl00&quot;, &quot;TemplateColumn&quot;, event); return false;__doPostBack('ctl00$MainContent$gvCompanyManagement$ctl00$ctl02$ctl02$Filter_TemplateColumn','')</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_MainContent_gvCompanyManagement_ctl00_ctl02_ctl02_Filter_TemplateColumn</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Filter</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rgFilter</value>
   </webElementProperties>
</WebElementEntity>
