<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Page 3 (City Result)</name>
   <tag></tag>
   <elementGuidId>0cd228cd-e205-48ad-bcf6-c65af5ae5680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_MainContent_gvCompanyManagement_ctl00_ctl06_Detail10&quot;]/tfoot/tr[2]/td/table/tbody/tr/td[2]/div[2]/a[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_MainContent_gvCompanyManagement_ctl00_ctl06_Detail10&quot;]/tfoot/tr[2]/td/table/tbody/tr/td[2]/div[2]/a[3]/span</value>
   </webElementProperties>
</WebElementEntity>
