<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ConsigneeCityCode_listbox</name>
   <tag></tag>
   <elementGuidId>fbeaa48a-9bea-4afe-beec-ded996bf389d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ConsigneeCityCode_listbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ConsigneeCityCode_listbox&quot;]</value>
   </webElementProperties>
</WebElementEntity>
