<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipperCountryCode_found</name>
   <tag></tag>
   <elementGuidId>38f356c7-86e5-40a8-ae95-e91002510033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tbl1&quot;]/tbody/tr[3]/td[2]/table/tbody/tr/td[2]/span/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl1&quot;]/tbody/tr[3]/td[2]/table/tbody/tr/td[2]/span/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
