<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>BC_logo</name>
   <tag></tag>
   <elementGuidId>a0f0c37e-c87d-4ce6-8516-74687e8cd88d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.logo-lg > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='page-topbar']/div/div/a/span[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>708b5f91-8f7b-4f27-b9a8-5dba677c7278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bookingconcierge2.dev.ccn/src/app/layouts/components/header/images/BCLogo.aa439f2fa819a1cd6d37.png</value>
      <webElementGuid>a8f40f3d-5abe-4008-81fc-aeeb01340665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>52</value>
      <webElementGuid>630f2e56-5d6b-47f3-a9b5-5200ae602b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>210</value>
      <webElementGuid>76bf175c-38bc-47d3-aedd-ed032f8e6f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-topbar&quot;)/div[@class=&quot;navbar-header&quot;]/div[1]/a[@class=&quot;logo logo-dark&quot;]/span[@class=&quot;logo-lg&quot;]/img[1]</value>
      <webElementGuid>feb7a901-1556-484f-9143-7fcdd37a6e45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='page-topbar']/div/div/a/span[2]/img</value>
      <webElementGuid>aab3980c-f1d3-4abb-9ea0-06fa7a730dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://bookingconcierge2.dev.ccn/src/app/layouts/components/header/images/BCLogo.aa439f2fa819a1cd6d37.png')])[2]</value>
      <webElementGuid>ca0e893f-3889-4939-88bf-a45b1abd6caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>24920f1f-26af-4a02-a862-328cb383e4b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://bookingconcierge2.dev.ccn/src/app/layouts/components/header/images/BCLogo.aa439f2fa819a1cd6d37.png']</value>
      <webElementGuid>b3921e35-4657-43eb-835c-c0cda62a66bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
