<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Freight Blocked Space - Fixed</name>
   <tag></tag>
   <elementGuidId>595cc62c-924f-4b42-80ee-bee6577878df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_RadMenu1&quot;]/ul/li[3]/div/ul/li[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_RadMenu1&quot;]/ul/li[3]/div/ul/li[2]/a/span</value>
   </webElementProperties>
</WebElementEntity>
