<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContractNumber_input</name>
   <tag></tag>
   <elementGuidId>64c93226-ac82-4ca5-bb3b-69bb54015f1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ContentPlaceHolder_SubPageContent_txtContractNumber&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ContentPlaceHolder_SubPageContent_txtContractNumber&quot;]</value>
   </webElementProperties>
</WebElementEntity>
