<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CustomerVendorCode_input-found</name>
   <tag></tag>
   <elementGuidId>8f2440d0-f7b7-46cd-87bc-4546802694aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ContentPlaceHolder_SubPageContent_txtCustomerVendorCode&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ContentPlaceHolder_SubPageContent_txtCustomerVendorCode&quot;]</value>
   </webElementProperties>
</WebElementEntity>
