<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__mat-end-date mat-date-range-input-inner ng-touched ng-dirty ng-valid</name>
   <tag></tag>
   <elementGuidId>268c8d4f-e4cc-4f51-96f5-0c22bb5f3bb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.mat-end-date.mat-date-range-input-inner.ng-touched.ng-dirty.ng-valid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>dateTo</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>End date</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-end-date mat-date-range-input-inner ng-touched ng-dirty ng-valid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/home[@class=&quot;ng-star-inserted&quot;]/main[@class=&quot;m-3&quot;]/app-report-form[@class=&quot;ng-star-inserted&quot;]/mat-card[@class=&quot;mat-card mat-focus-indicator mat-elevation-z4 report-form ml-auto mr-auto&quot;]/form[@class=&quot;mr-3 ml-3 mb-5 ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;row mb-4&quot;]/div[@class=&quot;d-flex w-100 mb-2&quot;]/div[@class=&quot;w-50 pr-4&quot;]/mat-form-field[@class=&quot;mat-form-field w-100 ng-tns-c75-0 mat-primary mat-form-field-type-mat-date-range-input mat-form-field-appearance-outline mat-form-field-can-float mat-form-field-has-label mat-form-field-should-float ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;mat-form-field-wrapper ng-tns-c75-0&quot;]/div[@class=&quot;mat-form-field-flex ng-tns-c75-0&quot;]/div[@class=&quot;mat-form-field-infix ng-tns-c75-0&quot;]/mat-date-range-input[@class=&quot;mat-date-range-input ng-tns-c75-0 mat-date-range-input-hide-placeholders ng-touched ng-dirty ng-valid&quot;]/div[@class=&quot;mat-date-range-input-container&quot;]/div[@class=&quot;mat-date-range-input-end-wrapper&quot;]/input[@class=&quot;mat-end-date mat-date-range-input-inner ng-touched ng-dirty ng-valid&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
   </webElementXpaths>
</WebElementEntity>
