<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CarrierCustCodePP_clear</name>
   <tag></tag>
   <elementGuidId>5c6adece-cd97-4825-95ca-c8aa6b5dc949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;CustomerCodePrePaid-list&quot;]/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;CustomerCodePrePaid-list&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
