<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccInfoCargoClass</name>
   <tag></tag>
   <elementGuidId>3b037b37-50a0-4b3e-8415-22d99be22108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl2&quot;]/tbody/tr[2]/td[2]/table/tbody/tr/td[2]/div/span/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
