<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipperCountryCode_list</name>
   <tag></tag>
   <elementGuidId>5a134039-71bd-412e-95f0-0d6b0fed1ff4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ShipperCountryCode-list&quot;]/</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ShipperCountryCode-list&quot;]/</value>
   </webElementProperties>
</WebElementEntity>
