<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Manage Air Cargo Rates</name>
   <tag></tag>
   <elementGuidId>fbfe90ba-f678-450c-ad94-ed85786158e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_Content_Content_rwdAssignStation_C_gvAssignProductToStation_ctl00_ctl12_chkAssigned&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_Content_Content_rwdAssignStation_C_gvAssignProductToStation_ctl00_ctl12_chkAssigned&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_Content_Content_rwdAssignStation_C_gvAssignProductToStation_ctl00_ctl12_chkAssigned</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$Content$Content$rwdAssignStation$C$gvAssignProductToStation$ctl00$ctl12$chkAssigned</value>
   </webElementProperties>
</WebElementEntity>
