<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CargoClass_input-found</name>
   <tag></tag>
   <elementGuidId>231560b6-f2a4-4001-a6d1-de85ad9e57ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbCargoClass_DropDown&quot;]/div[2]/ul/li[4]/table/tbody/tr/td[1][count(. | //*[(text() = 'GEN' or . = 'GEN')]) = count(//*[(text() = 'GEN' or . = 'GEN')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbCargoClass_DropDown&quot;]/div[2]/ul/li[4]/table/tbody/tr/td[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GEN</value>
   </webElementProperties>
</WebElementEntity>
