<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_26060005</name>
   <tag></tag>
   <elementGuidId>df9f2269-702a-4af2-9ca8-14f383442eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'26060005')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td.ccn-common-table-td > a.ccn-wc-bc-booking-details-awb-lookup-item</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fac39c40-7809-40b8-b9ef-d40b3cec7c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-wc-bc-booking-details-awb-lookup-item</value>
      <webElementGuid>6b35096d-0bf8-4c4c-9506-9e5f2689ebf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26060005</value>
      <webElementGuid>f640c3f0-6288-4407-974a-08bd2b8cab7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[4]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog ccn-wc-bc-booking-details-awb-lookup-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ccn-common-modal-body modal-body&quot;]/div[@class=&quot;ccn-common-table-container&quot;]/div[@class=&quot;ccn-common-table-no-legend&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[4]/td[@class=&quot;ccn-common-table-td&quot;]/a[@class=&quot;ccn-wc-bc-booking-details-awb-lookup-item&quot;]</value>
      <webElementGuid>816d6a3b-64ca-43a2-9edd-0a7f6b96ab86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'26060005')]</value>
      <webElementGuid>52795172-6600-48b3-a90c-762c455a26bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total New Stock'])[1]/following::a[4]</value>
      <webElementGuid>f009858f-b267-40b5-8fb5-1bace7cc18cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWB Suffix'])[1]/following::a[4]</value>
      <webElementGuid>2a16417c-2c96-42d9-b475-7a42a10246cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items per page:'])[1]/preceding::a[7]</value>
      <webElementGuid>8bd978f2-f501-4272-9ccd-39a44f13b314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::a[7]</value>
      <webElementGuid>cc6098d1-4be7-4b01-95c4-fa92ccf41c59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='26060005']/parent::*</value>
      <webElementGuid>72a9402a-d13a-4e74-9424-ea9d9941fc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/a</value>
      <webElementGuid>b16b1265-0c15-4ba9-b5c3-16a7a1d9658e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '26060005' or . = '26060005')]</value>
      <webElementGuid>3fb4a41c-b3a3-4e9a-b522-e30e0cf34a62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
