<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SQ0714</name>
   <tag></tag>
   <elementGuidId>05a35a53-d48e-404a-971f-fd2ecd8aabde</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='SIN to BKK'])[1]/following::a[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.ccn-common-table-td > table.ccn-ccn-wc-bc-flight-schedule-result-table-Row > tbody > tr > td.ccn-common-table-td > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd5879ae-3404-4880-a3ba-ecd2f6433332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQ0714</value>
      <webElementGuid>907b56c5-c4bf-470b-a362-9631ca1bd7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[4]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog ccn-wc-bc-flight-schedule-modal modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ccn-common-modal-body modal-body&quot;]/span[@class=&quot;ccn-common-elevated-paper-container&quot;]/div[@class=&quot;ccn-common-elevated-paper ccn-wc-bc-flight-schedule-result-container&quot;]/div[@class=&quot;ccn-common-table-container&quot;]/div[@class=&quot;ccn-common-table-no-legend&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[2]/td[@class=&quot;ccn-common-table-td&quot;]/table[@class=&quot;ccn-ccn-wc-bc-flight-schedule-result-table-Row&quot;]/tbody[1]/tr[1]/td[@class=&quot;ccn-common-table-td&quot;]/a[1]</value>
      <webElementGuid>eb18151b-392c-45d0-bd46-ad6b36066fd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIN to BKK'])[1]/following::a[1]</value>
      <webElementGuid>1fbc2de0-3cc7-49fc-8d0f-ec71be93e204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TR0616'])[1]/following::a[1]</value>
      <webElementGuid>216666b4-d41c-4615-84da-f0809a2d1c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIN to BKK'])[2]/preceding::a[1]</value>
      <webElementGuid>05533a66-51bf-4769-8795-6af5bc7288bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TR0610'])[1]/preceding::a[1]</value>
      <webElementGuid>04a7e573-2194-466a-aec7-794dba94df7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SQ']/parent::*</value>
      <webElementGuid>950fbfe3-c956-48e9-ab8e-9616b2872371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/a</value>
      <webElementGuid>a1b04a6f-127e-467b-b75e-b08ce13751c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'SQ0714' or . = 'SQ0714')]</value>
      <webElementGuid>6835d47d-38e6-44d3-b2c2-84098dd26b13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
