<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_My Airlines</name>
   <tag></tag>
   <elementGuidId>f158f663-5e28-41b5-92d6-6ffc3c022362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/span/div/button[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.mx-2.d-none.d-md-block.my-airlines-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9f822bd7-7c70-4e10-ba9c-8a91531b7b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mx-2 d-none d-md-block my-airlines-button</value>
      <webElementGuid>9c2229b1-e271-4a67-bcd2-f183864bbd3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>My Airlines</value>
      <webElementGuid>07b40286-3a7b-4072-a113-8c0967155fe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;bc-dashboard-container m-3&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;bg-transparent&quot;]/div[@class=&quot;py-3 navigation-buttons&quot;]/span[1]/div[@class=&quot;right-navigation-button&quot;]/button[@class=&quot;btn btn-primary mx-2 d-none d-md-block my-airlines-button&quot;]</value>
      <webElementGuid>8dcca49f-929e-42f8-acd9-b8f07599a297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/span/div/button[2]</value>
      <webElementGuid>557a7c34-e0a2-4801-965a-c78fe608fd5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Booking'])[1]/preceding::button[1]</value>
      <webElementGuid>bfa4d5a5-2be4-4d99-829c-04ebd3f0f7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REGJULY'])[1]/preceding::button[1]</value>
      <webElementGuid>3b858ac1-1df0-4ef2-8d73-5e4b08826fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='My Airlines']/parent::*</value>
      <webElementGuid>b55966b1-9836-4f9c-8883-35b69335c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e464b423-8aea-4802-94d1-38932f2771c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'My Airlines' or . = 'My Airlines')]</value>
      <webElementGuid>30391993-0ed9-4692-88b6-508b84952224</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
