<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__awbPrefix</name>
   <tag></tag>
   <elementGuidId>8ef28df9-3d60-49ac-98d4-3de20f26e617</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='awbPrefix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#awbPrefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>370695f3-cc8f-4e2d-87e3-233edc6529bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>111</value>
      <webElementGuid>b860ed9b-7bb1-41b2-8fa6-bc7bca4f3fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>06294b0f-7e55-4a8d-802f-2b1ab72fe665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a4b8d112-e317-4231-867a-34c50346b69f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awbPrefix</value>
      <webElementGuid>142652a5-a081-4059-82f9-d7ba22c87b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>awbPrefix</value>
      <webElementGuid>db60bc11-c337-4727-9fb6-3c4723c74659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76941b2e-d95f-4b4d-ac7d-b6ca0d6464c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input ccn-common-awb-prefix form-control</value>
      <webElementGuid>88a46c57-53c7-4309-8271-18418ad10abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df615776-1591-47b1-8317-8341166ad3b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;awbPrefix&quot;)</value>
      <webElementGuid>d109d523-f24f-403d-8424-7702dd90e20c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='awbPrefix']</value>
      <webElementGuid>85a2cd43-c8e6-47a0-a480-7ced58b6d642</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div/div/div/div/label/div/span/input</value>
      <webElementGuid>53e0f889-bf01-4e54-bbc0-eb425774791c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>cb56f6e7-9ee4-4bc4-a076-57f1adb9fd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '111' and @name = 'awbPrefix' and @id = 'awbPrefix' and @type = 'text']</value>
      <webElementGuid>6cac4215-27a1-4a9d-bbd4-05035bafc7e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
