<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PI_cargoPackingInstruction</name>
   <tag></tag>
   <elementGuidId>7c03e4c1-f3a1-4612-b089-000d5f5eeda3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cargoPackingInstruction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cargoPackingInstruction&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37be0667-2940-419d-922d-5047adb76234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Packing Instruction</value>
      <webElementGuid>559ee7fa-f6fd-49b8-913b-b0f64b286e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cargoPackingInstruction</value>
      <webElementGuid>4a945a35-a47f-4e62-b028-bb111ab15c16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>dc856d02-7df9-4a11-b4d9-e1103e4bc34d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76a959d4-3d36-44fe-874c-47ff7fdb4ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input ccn-border-bottom-hover-secondary-primary form-control</value>
      <webElementGuid>3261f6ed-c83f-4bfe-8995-93d3ea528e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9697f6cc-2cca-4c2b-8070-84e8deda3faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[4]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog ccn-wc-bc-dgi-modal modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ccn-common-modal-body modal-body&quot;]/div[@class=&quot;ccn-wc-bc-dangerous-goods-input d-flex justify-content-between align-items-center&quot;]/div[1]/span[@class=&quot;ccn-common-input-container&quot;]/input[@class=&quot;ccn-common-input ccn-border-bottom-hover-secondary-primary form-control&quot;]</value>
      <webElementGuid>3185f744-6922-4ea0-b8b1-3d7c62813863</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cargoPackingInstruction']</value>
      <webElementGuid>85ae7f7e-542a-4228-9e95-d3568a68822a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/span/input</value>
      <webElementGuid>392be7e8-df76-4597-9b1a-51b22dd501bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Packing Instruction' and @name = 'cargoPackingInstruction' and @type = 'text']</value>
      <webElementGuid>b88537ef-baa3-4348-b501-a4a3e9c4ff12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
