<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Carrier Code_carrierCode</name>
   <tag></tag>
   <elementGuidId>6d514cf4-fc30-4af6-a96c-9b82a6f18a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CCNWCBCFlightScheduleCarrierCode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CCNWCBCFlightScheduleCarrierCode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>69f7e944-a4cf-43a1-806f-569be3f56b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>A1</value>
      <webElementGuid>ee506e3d-0a2c-4ac7-9a90-5c036f72bb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7e18ca90-a781-42c9-bd07-b3e4a381b945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Carrier Code</value>
      <webElementGuid>ad3a52b6-fdf9-4c72-a727-0a7058f4cd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNWCBCFlightScheduleCarrierCode</value>
      <webElementGuid>cf54f11a-7160-4583-9127-66b7b2b33f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrierCode</value>
      <webElementGuid>283ccd1e-68b4-4cb3-87d4-ea57c15cf009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validation</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c83bb0a5-67ac-4e60-9d50-769be6f04b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0abe3570-9201-4603-8acd-f01b2af9f443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d6d3d9d-b433-4b7c-9f6b-556a3aaad102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input ccn-common-input-floating-label form-control</value>
      <webElementGuid>1bc1b793-b2c9-4cb9-a529-ce0e4760d3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SQ`</value>
      <webElementGuid>816dbc4e-e01c-4b36-9d8d-f9366fc1e57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNWCBCFlightScheduleCarrierCode&quot;)</value>
      <webElementGuid>a22e491c-fa6a-4afb-8ea4-daf649afc0a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CCNWCBCFlightScheduleCarrierCode']</value>
      <webElementGuid>ba1c7ea8-4354-4b43-b940-0cda7cdf6953</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>2e6bdf8b-53eb-4638-bd2a-92931d479778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'A1' and @id = 'CCNWCBCFlightScheduleCarrierCode' and @name = 'carrierCode' and @type = 'text']</value>
      <webElementGuid>f4355841-40cf-48a7-8e81-3b444a8a4763</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
