<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Benzaldehyde</name>
   <tag></tag>
   <elementGuidId>1ccc88e9-62f6-49cd-b1ab-7fc6cf27fcb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='Benzaldehyde0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Benzaldehyde0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>2ec2057c-c122-475f-bd0e-4841b429fd64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input-dropdown-item</value>
      <webElementGuid>8cf127f5-3dd3-464c-ae71-ffa2021028f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Benzaldehyde0</value>
      <webElementGuid>ca474f43-8286-49d8-81de-80a446ce8660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benzaldehyde</value>
      <webElementGuid>7710e3c2-d4d4-479f-af36-cd8ff3b8c29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Benzaldehyde0&quot;)</value>
      <webElementGuid>3d1ba910-ae47-4070-9d5a-e7307b4a6087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='Benzaldehyde0']</value>
      <webElementGuid>ef959e0e-1db9-491a-a768-2f297a8621d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proper Shipping Name'])[1]/following::li[1]</value>
      <webElementGuid>3c749bda-af0e-48f8-9fac-2a5824b1ad0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNID'])[2]/following::li[1]</value>
      <webElementGuid>4919e879-ac8f-4f43-9d33-2a2248a0e872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required.'])[1]/preceding::li[1]</value>
      <webElementGuid>56cdff70-e83e-4839-bf1d-7a0a078b7565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>d6cec16c-bbff-4c56-a1da-29e53b91ece0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'Benzaldehyde0' and (text() = 'Benzaldehyde' or . = 'Benzaldehyde')]</value>
      <webElementGuid>b9074845-9ef4-44a6-92e1-b28da2118fbe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
