<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_awbSuffix is a required field_awb-lookup-button</name>
   <tag></tag>
   <elementGuidId>a99a2e19-a8f6-49ce-adbc-5822eb18ab8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='awb-lookup-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#awb-lookup-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd5106fa-b622-490c-89c5-70545e04d0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-button-icon</value>
      <webElementGuid>7bdff82f-324d-4099-89f3-f7fc128131b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>awb-lookup-button</value>
      <webElementGuid>d1e59e5c-7237-49aa-b889-8672fc5f9c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;awb-lookup-button&quot;)</value>
      <webElementGuid>deaf7db8-d2c2-4f6a-be3e-d01a6d3d1134</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='awb-lookup-button']</value>
      <webElementGuid>32be5251-c36f-4141-a88f-3e7375e10839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div/div/div[3]/div/label/div/div/span</value>
      <webElementGuid>cf02fe2a-4bea-4984-adab-a78ae6793f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='awbSuffix is a required field'])[1]/following::span[1]</value>
      <webElementGuid>5d92e819-4caa-4e7a-95c4-cc8ec2e37416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/following::span[2]</value>
      <webElementGuid>0fd92ca1-d5d0-45b9-8b07-53982163ab37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/preceding::span[1]</value>
      <webElementGuid>c4013e20-9393-4196-8872-0364d1a66e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div/div/span</value>
      <webElementGuid>6f0ae4ff-41d7-4acc-a8e0-8983563eaee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'awb-lookup-button']</value>
      <webElementGuid>f47a48f9-b1aa-423f-b6d6-026935f2c8da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
