<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Operational_ccn-wc-bc-flight-section-search</name>
   <tag></tag>
   <elementGuidId>412a4009-36db-47d3-8b80-9f64a3ff5673</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='ccn-wc-bc-flight-section-search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ccn-wc-bc-flight-section-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1576b223-76a7-4d87-84a7-dfb6a5a6d46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-button-icon ccn-wc-bc-flight-section-search</value>
      <webElementGuid>addc3061-487a-4ab5-9c3c-3bb52e3c6a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccn-wc-bc-flight-section-search</value>
      <webElementGuid>66ae9d6f-1ad7-4bcf-9a32-4f7d9383edb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccn-wc-bc-flight-section-search&quot;)</value>
      <webElementGuid>ae3c6e8b-7196-413e-8b2d-56f4e7606225</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='ccn-wc-bc-flight-section-search']</value>
      <webElementGuid>98e1327d-c447-4dbc-a07c-9d019f8f3f35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[4]/span/div/span/div/div[2]/div/span</value>
      <webElementGuid>f936f88d-2690-4076-8990-8073b139c001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational'])[1]/following::span[1]</value>
      <webElementGuid>6aa0d0db-b78a-4f95-bf46-5e9ef098af31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::span[1]</value>
      <webElementGuid>ebcee5c7-8045-4461-939c-ae31249c582a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Number'])[1]/preceding::span[2]</value>
      <webElementGuid>3e69ad81-f533-41a2-b9d6-59edb999bf97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Date'])[1]/preceding::span[2]</value>
      <webElementGuid>ad327d9c-b3e6-4a1a-868d-f33206d2adc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div/div[2]/div/span</value>
      <webElementGuid>f9884d16-4bbf-4b0a-8ef7-788ab9ec7cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'ccn-wc-bc-flight-section-search']</value>
      <webElementGuid>59b62471-7827-4122-baad-b36aee23a6a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
