<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Shipper_CCNWCBCShipperMetaID</name>
   <tag></tag>
   <elementGuidId>fbb05f74-3245-4e3d-911f-b3eeeeeeb340</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='CCNWCBCShipperMetaID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CCNWCBCShipperMetaID</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>596d0eab-a97f-4e51-b376-455f96788ace</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-button-icon ccn-wc-bc-common-button-icon-add</value>
      <webElementGuid>897ada48-e658-492d-9088-9801b98e8e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNWCBCShipperMetaID</value>
      <webElementGuid>909d53e1-4337-4645-b622-52dbefcc41aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNWCBCShipperMetaID&quot;)</value>
      <webElementGuid>2798da79-3862-4803-bafe-024caaa1ce11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='CCNWCBCShipperMetaID']</value>
      <webElementGuid>af05f3c7-5690-425a-973f-0b5d86aa1909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[5]/span/div/div/div/span/div/div/div/span</value>
      <webElementGuid>17eeb210-6ec0-44fb-bd93-cdc57938a9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipper'])[1]/following::span[1]</value>
      <webElementGuid>03124d67-c051-4ea6-bc43-f6e19f3d7978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Allotment ID'])[1]/following::span[4]</value>
      <webElementGuid>77ee5137-8f8a-4746-bdc0-f117a7661fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[1]/preceding::span[1]</value>
      <webElementGuid>eeafa8e4-0531-45f5-a5c0-83d409813c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No'])[1]/preceding::span[1]</value>
      <webElementGuid>ae0204aa-3c8e-42fb-b747-ef4a044f4428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/div/div/div/span</value>
      <webElementGuid>f5375533-cb44-4d0e-b4b3-37437e3215f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'CCNWCBCShipperMetaID']</value>
      <webElementGuid>830ac408-7880-401a-ad5c-e4393982dd49</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
