<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_UpdateProfile</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>ac2cccc4-680e-4ce6-8f3b-5de02a0e40a3</testSuiteGuid>
   <testCaseLink>
      <guid>3b6a1c40-508b-4d93-8154-60adcf3a71cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication Login/Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d96d93b4-ad59-48e4-b937-afdf7baba0a2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 2/Login to Booking Concierge/0 Login Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2020a495-7060-4f34-b7e9-4f3017b45cf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b99673a-7f6b-4e9b-ae57-42b8ef9938e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>64deb2f6-02ec-4e49-a12c-9eba36c1da92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 7/Profile/0 Update Profile (Edit Password)2</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99367efb-f10a-42ac-8eb1-5116a3523a2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>058fe5cb-7c04-490e-ae5e-32d30cbbd058</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1f96fa4c-5eec-4ac7-8c31-05453b314886</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
