<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_20722015</name>
   <tag></tag>
   <elementGuidId>caa637b2-8325-4d61-b8ab-eb9b860b605c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'20722015')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19c9e3c4-0c47-4b2e-ad9e-083714ab13f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-BC__BookingDetails-AWB-Lookup-Item </value>
      <webElementGuid>c672f422-542f-4535-8b5a-f3f50f88f665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20722015</value>
      <webElementGuid>a393ab97-3db6-4b17-a293-179f5ca32903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog ccn-BC__BookingDetails_AWB_Lookup_Dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[1]/div[2]/div[@class=&quot;theme-module_table-responsive__mpPWz theme-module_text-center__eekOx&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[8]/td[@class=&quot;theme-module_px-0__Mkptd theme-module_py-3__0OpzX&quot;]/a[@class=&quot;ccn-BC__BookingDetails-AWB-Lookup-Item&quot;]</value>
      <webElementGuid>1afdce87-bb31-4660-885e-52d1578532aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'20722015')]</value>
      <webElementGuid>1433cf3b-81c5-4390-8167-a4b7df4157c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total New Stock'])[1]/following::a[8]</value>
      <webElementGuid>e12ecf04-a297-4a36-8b17-45023d7d3361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AWB Suffix'])[1]/following::a[8]</value>
      <webElementGuid>e535ca72-298e-45d1-bebe-7bd369532957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='&lt;'])[1]/preceding::a[3]</value>
      <webElementGuid>dab92b31-c308-4ad9-80b5-25beb485da45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='>'])[1]/preceding::a[3]</value>
      <webElementGuid>9cc4ff20-6861-45c3-8fc3-afcef9289a25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20722015']/parent::*</value>
      <webElementGuid>1232ba3b-b534-4b8a-b842-aac402948cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/a</value>
      <webElementGuid>454c1ccc-4783-46d0-a47f-4b820657b2bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '20722015' or . = '20722015')]</value>
      <webElementGuid>27cb523b-7081-4381-9735-fb166090e868</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
