<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Consignee_ccn-CCNWCBCConsignee-AddButton</name>
   <tag></tag>
   <elementGuidId>0ef90d08-12b0-4611-a29f-eb730c9b94da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ccn-CCNWCBCConsignee-AddButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/form/div[7]/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9712873d-11b8-4798-bcff-f353a1811f16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-CCNWCBCConsignee-AddButton</value>
      <webElementGuid>11f32e95-4596-4476-a74d-ad39ebc435bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-content&quot;]/form[@class=&quot;booking-form&quot;]/div[@class=&quot;ccn-CCNWCBCConsignee&quot;]/div[@class=&quot;theme-module_ElevatedPaper__-PaWa&quot;]/div[@class=&quot;ccn-CCNWCBCConsignee-PaperHeader&quot;]/div[@class=&quot;ccn-CCNWCBCConsignee-AddButton&quot;]</value>
      <webElementGuid>e04d0f8e-62c2-4c41-a592-68aa2990ac56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[7]/div/div/div</value>
      <webElementGuid>afe8582f-e7e8-4e71-a164-76b027b5cbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consignee'])[1]/following::div[1]</value>
      <webElementGuid>9e4c20aa-9bba-4009-b1af-0bd9514b489d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SG'])[1]/following::div[5]</value>
      <webElementGuid>90112b66-dd22-4465-b39a-6d30246d336f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code'])[2]/preceding::div[1]</value>
      <webElementGuid>5b175557-ed1d-447e-bcdf-85532c959229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account No'])[2]/preceding::div[1]</value>
      <webElementGuid>7da07d36-fcf0-4355-b307-c9c7e6608ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div</value>
      <webElementGuid>bb704169-363a-4c2a-a743-5e0ec9bcc06f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
