<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dangerous Goods Information_CCNBC-Dange_a89f46</name>
   <tag></tag>
   <elementGuidId>80a30e26-151a-444d-aed7-342172b274c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CCNBC-DangerousGoods-Add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CCNBC-DangerousGoods-Add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf1da82e-c323-4291-9f2e-361060dcf394</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNBC-DangerousGoods-Add</value>
      <webElementGuid>19999a71-9249-48a1-b2de-3bd7154c6160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-CCNCommonAddButton-circle-add-button</value>
      <webElementGuid>c49bab19-b344-49d7-8375-ebab1c81cb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNBC-DangerousGoods-Add&quot;)</value>
      <webElementGuid>d4d11194-7c90-4640-830e-c295fcc7ed17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='CCNBC-DangerousGoods-Add']</value>
      <webElementGuid>9c8daaaf-f054-4dd8-bfe6-03e1c52cca92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[3]/div/div/div/div/div</value>
      <webElementGuid>0586b647-ac30-4f35-9e5b-c58d38b5cf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIN'])[1]/following::div[6]</value>
      <webElementGuid>b55bc67f-0c4a-4e2b-85db-84cb705986d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNID'])[1]/preceding::div[1]</value>
      <webElementGuid>dad49349-4ac0-4243-9c39-c3ef0bd5db52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Name'])[1]/preceding::div[1]</value>
      <webElementGuid>4e431018-6aed-4904-a40a-e0ba0929729e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>fa684975-908e-4510-b949-c015845249e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'CCNBC-DangerousGoods-Add']</value>
      <webElementGuid>563e3276-9f3d-402a-af50-6ec76b36f6a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
