<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dangerous Goods Information_CCNBC-Dange_a89f46</name>
   <tag></tag>
   <elementGuidId>80a30e26-151a-444d-aed7-342172b274c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CCNBC-DangerousGoods-Add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='CCNBC-DangerousGoods-Add']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98ec889d-290d-4465-b3ab-d08a3cf26a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNBC-DangerousGoods-Add</value>
      <webElementGuid>2ea51fc3-5440-4772-898f-25fd08956b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-CCNCommonAddButton-circle-add-button</value>
      <webElementGuid>1f82c373-3904-441a-b3e7-8a6bb11d45f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNBC-DangerousGoods-Add&quot;)</value>
      <webElementGuid>69a2f972-6ffd-450b-974c-664568fa827e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='CCNBC-DangerousGoods-Add']</value>
      <webElementGuid>ee55f8fe-1d77-4482-a6a0-15cb41e4233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[3]/div/div/div/div/div</value>
      <webElementGuid>96c1e230-20c8-4c5a-9ca4-4d6fa3edd325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SIN'])[1]/following::div[6]</value>
      <webElementGuid>c7e2c257-5f3c-4352-a176-a58621bf65f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNID'])[1]/preceding::div[1]</value>
      <webElementGuid>3d50627d-db18-4e96-be14-aafb3b30290b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipping Name'])[1]/preceding::div[1]</value>
      <webElementGuid>0b9087c6-0c85-464f-b799-077272749544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div</value>
      <webElementGuid>cd811527-4c87-4178-bdfb-76c48b41fd9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'CCNBC-DangerousGoods-Add']</value>
      <webElementGuid>59800650-bdb3-4c35-a803-01bf01376ea4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
