<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Operational_ccn-CCNWCBCFlightSection-search</name>
   <tag></tag>
   <elementGuidId>365028e3-d9d5-4192-99e9-ea727f717baf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccn-CCNWCBCFlightSection-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ccn-CCNWCBCFlightSection-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c93accd8-a8b5-44ed-97cd-2ecd46854b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccn-CCNWCBCFlightSection-search</value>
      <webElementGuid>4089c8c8-36cb-4402-bc73-680128ec940e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-CCNCommonCircleSearchButton undefined</value>
      <webElementGuid>c3e4b0a2-c692-4f36-a817-ecb7394d8a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccn-CCNWCBCFlightSection-search&quot;)</value>
      <webElementGuid>bbf17b4e-4b7a-4629-9519-f77740c989d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ccn-CCNWCBCFlightSection-search']</value>
      <webElementGuid>5f3cb513-fa1d-48b5-8205-5dd3f6b5a22d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[4]/div/div/div[2]/div/div</value>
      <webElementGuid>01af2604-68b1-445e-89d8-4b2e4eaa1420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operational'])[1]/following::div[3]</value>
      <webElementGuid>4e703cf0-c18e-4a79-9e88-4b34a3d8110a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flights'])[1]/following::div[4]</value>
      <webElementGuid>38de0fa9-4bcd-41f3-830a-e8835e9e672d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Number'])[1]/preceding::div[3]</value>
      <webElementGuid>0bfa8afe-35c3-4497-9797-9bdc5a56f1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Flight Date'])[1]/preceding::div[3]</value>
      <webElementGuid>5ebdb083-8e7e-4c73-ac7a-2207fabe9c76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div</value>
      <webElementGuid>1a3630cf-1a4a-41e3-98cf-f2bc961feb8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ccn-CCNWCBCFlightSection-search']</value>
      <webElementGuid>88e62a81-14c0-48de-ae8a-e440161aa33c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
