<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Dangerous Goods Information_bx bx-plus</name>
   <tag></tag>
   <elementGuidId>e31706bd-be1f-45f0-8209-8bb4776809e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unit-loading-device-section > i.bx.bx-plus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='unit-loading-device-section']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aaf52d09-7ad5-4c62-8041-cd6c01c9cac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-plus</value>
      <webElementGuid>92637a85-1ba4-4cff-8a90-d36cb8cacf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unit-loading-device-section&quot;)/i[@class=&quot;bx bx-plus&quot;]</value>
      <webElementGuid>ba4c4eab-cdf6-490d-b62d-7ab1777482cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='unit-loading-device-section']/i</value>
      <webElementGuid>1c0e1117-8d4a-4dbb-9d91-c196048be1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div/div/i</value>
      <webElementGuid>936d0867-4e17-47d4-b2a2-3bbda91c331c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='insurance-add']/i</value>
      <webElementGuid>81f244a1-9f78-496e-9485-2f172f4bc611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/button/i</value>
      <webElementGuid>48ffea6d-0bad-4fb5-9537-a136fdcdad71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[5]/div/div[2]/table/tbody/tr/td[11]/span/i</value>
      <webElementGuid>7c314025-c3a4-416c-badd-886b0d1d9efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/span/i</value>
      <webElementGuid>cedccbca-2dbc-4a49-90c6-7a533888a660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div[5]/div/div/div/i</value>
      <webElementGuid>df25802f-6bd5-41b6-9273-f149376b1975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/i</value>
      <webElementGuid>c7969168-f191-4e1c-90bb-5e9d6c28907c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='awb-lookup-button']/i</value>
      <webElementGuid>2f4fe2ac-45d7-4003-b38f-fbc7f9babd9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/i</value>
      <webElementGuid>1c07bbb1-5f46-496f-9da9-262b702a7db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='CCNBC-DangerousGoods-Add']/i</value>
      <webElementGuid>acf74e19-434c-4f1d-ad97-e20e1e5df66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/i</value>
      <webElementGuid>da242332-3c55-42db-8ef7-62bbcb348546</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
