<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_postalCode_1</name>
   <tag></tag>
   <elementGuidId>8995be83-4f4c-44e2-ba48-4e2f2c7cf5e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postalCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postalCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae5d40a4-f055-4beb-8cd4-8f498bce6de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d5a4a676-8c56-4f2d-acea-807e2fbe572e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>27925259-c8dd-46c8-9149-85ec2c8a7eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postalCode</value>
      <webElementGuid>ce599317-8eaa-41cf-bd77-30155c5253f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7c4025f9-2db8-4dc7-9402-b4a1a5dad521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>e0ea4104-7d54-41e6-ba9c-01b0d7d1b490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Shipper Postal Code</value>
      <webElementGuid>15ff6b39-0c65-43de-9e86-ae5a1a1bf291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43cb0ae1-b3eb-458d-857b-0e09614ada4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG form-control</value>
      <webElementGuid>ea90dbf1-cc59-4751-9a0f-a0ae2eb997e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postalCode&quot;)</value>
      <webElementGuid>5895ec58-ae4e-4a3f-9570-95ebe417dd90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postalCode']</value>
      <webElementGuid>4fd6b0b9-fb16-41d0-91c7-f2c467a463aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div/input</value>
      <webElementGuid>edc746bf-361e-427e-aa78-4540d9b35b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'postalCode' and @id = 'postalCode' and @placeholder = 'Shipper Postal Code' and @type = 'text']</value>
      <webElementGuid>2ae473fa-daa1-43ee-a0bc-ed18147161bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
