<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Goods Value(SGD)_goodsValue</name>
   <tag></tag>
   <elementGuidId>9e549d86-88de-4c46-a631-bc4417adf934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goodsValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='goodsValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db044824-6c9a-45fa-ada8-c4a9f980b1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fedb9e7c-0552-4eff-8b67-9ee6a2f93163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goodsValue</value>
      <webElementGuid>c47fffc4-fbcd-400c-990b-2f28117b2c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goodsValue</value>
      <webElementGuid>86127f57-3260-4108-a6e5-2b3f2b649781</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>14c7f4e7-47b7-430b-816b-38677e6ea2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1111111.11</value>
      <webElementGuid>9e43ef9c-7757-4c86-9d12-81dd5aff4f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0956bbc4-2c22-4508-b730-8d6e4f9266df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG form-control</value>
      <webElementGuid>ccf8578c-fcbc-4acf-a6e1-06a9129648f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goodsValue&quot;)</value>
      <webElementGuid>8705431a-16c5-4b20-a696-5e0d4c0be9ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='goodsValue']</value>
      <webElementGuid>05eb1f39-379f-456a-af38-17347bf8140b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>9247059c-8228-4a2c-84e2-31a431f52303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'goodsValue' and @id = 'goodsValue' and @placeholder = '1111111.11' and @type = 'number']</value>
      <webElementGuid>72577c56-f736-4d14-a0be-fd2241a05c13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
