<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Special Handling Codes_specialHandlin_8a0d5a</name>
   <tag></tag>
   <elementGuidId>84ad05ca-0155-4b88-9775-fec690498890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#specialHandlingCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='specialHandlingCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15d546a0-6565-4285-b87c-838969cdf88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c2296b77-9e8f-48c3-b8b1-fb800d7c0565</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>specialHandlingCode</value>
      <webElementGuid>52354119-e3cd-4298-9277-a3297d878e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specialHandlingCodes[0].code</value>
      <webElementGuid>84c21532-d62e-4763-a903-3c3a090ceaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>42801c23-4cac-4e96-80c2-d3bed5e744eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5a4b165f-be6e-435d-8578-46d63bb76919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AAA</value>
      <webElementGuid>45954a4e-77b4-41b4-beba-ed8aa8959883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05e2dab0-6168-4725-9b12-57db824b2ddf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>80eda71a-e879-4e1d-b536-a3d48aef7ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c9e7ac74-076e-4be6-865e-e3e1c7ca971e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-content&quot;]/form[@class=&quot;booking-form&quot;]/div[@class=&quot;ccn-BC__BookingDetails&quot;]/div[@class=&quot;theme-module_ElevatedPaper__-PaWa theme-module_pb-0__v396a&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;theme-module_card__5p5Cl&quot;]/div[@class=&quot;theme-module_card-body__rJq5X&quot;]/div[@class=&quot;ml-2 theme-module_p-2__Y647L theme-module_pb-2__8fUif row&quot;]/div[@class=&quot;w-7 m-0 px-2.5 py-1 col-sm-1&quot;]/div[@class=&quot;ccn-CCNCommonCodeInputWithDropdown&quot;]/input[@id=&quot;specialHandlingCode&quot;]</value>
      <webElementGuid>4af22756-fba9-4f27-b85a-c285219573f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='specialHandlingCode']</value>
      <webElementGuid>7f19a370-2874-4d56-933c-a44ce024b0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div[2]/div/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>d9b35ccb-4110-4dbe-9273-981f81920617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>47708241-141e-4a0f-9898-7cccf8ca7f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'specialHandlingCode' and @name = 'specialHandlingCodes[0].code' and @placeholder = 'AAA' and @type = 'text']</value>
      <webElementGuid>881ad497-31c7-477c-8fb1-8264166dadda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
