<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_-_awbSuffix</name>
   <tag></tag>
   <elementGuidId>919a3bd9-e9ac-486c-ae1e-2338309c3db7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='awbSuffix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#awbSuffix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d1fe789-8caa-4a95-8129-85304040dc8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>11111111</value>
      <webElementGuid>7f5738f4-3219-43b2-b5e2-ad8040ba5480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>f6950c54-559d-40f3-ad03-9c0f4c27feff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1ecbb393-2e9f-48ca-a4e8-382d2b72f8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>8a53ca98-e382-48c1-8777-54334712f60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>awbSuffix</value>
      <webElementGuid>5fc6fdad-6585-47d7-8e1a-8e4949443531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>awbSuffix</value>
      <webElementGuid>4dec463d-1e17-4cd7-bb40-9e525b2fd601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9ed68958-ac2e-4467-853c-781e27642ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input ccn-common-awb-suffix form-control</value>
      <webElementGuid>996100e4-9d38-4f0b-9352-b06dd9c5dc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da78b443-fa91-40a4-bfa2-ce7cc38ff4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;awbSuffix&quot;)</value>
      <webElementGuid>61607c2b-8b49-452d-a42d-910ec10f0265</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='awbSuffix']</value>
      <webElementGuid>92bf64e7-7ca7-44ba-abd8-a0d7653c747a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div/div/div/div[2]/div/label/div/span/input</value>
      <webElementGuid>716277b8-f6dd-44bf-be3b-c8c5d8d0257e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label/div/span/input</value>
      <webElementGuid>47d3e75b-eef1-428d-90db-c9691a0e89bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '11111111' and @name = 'awbSuffix' and @id = 'awbSuffix' and @type = 'text']</value>
      <webElementGuid>c9a68eaf-2e43-4154-a5b7-9f5deffc8396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
