<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No of Packages_numberOfPackages</name>
   <tag></tag>
   <elementGuidId>0fb62dcc-8371-44eb-b313-16dde1d921bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;numberOfPackages&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='numberOfPackages']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7c8c162-4a2f-458b-bc4b-0400f8a6b114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>25b5a1e9-5951-4751-8e84-56a975c85a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>numberOfPackages</value>
      <webElementGuid>ec250fed-9e6a-429f-bf3e-9d05346258be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d7d5204-bb21-4973-a68f-d8b2a2dd6b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>e6a2c0d8-86e7-4f0e-a5cd-df7d45c4f0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG  form-control</value>
      <webElementGuid>c5fabf48-e7ae-445b-8726-6c962cf1e258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd18dfc0-4166-460c-a155-7a9c463c71e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ccn-CCNWCBCDangerousGoodsDetails-Input d-flex justify-content-between align-items-center&quot;]/div[@class=&quot;ccn-CCNWCBCDangerousGoodsDetails-InputField&quot;]/input[@class=&quot;theme-module_form-control__0sG2o theme-module_border-bottom__unqVG  form-control&quot;]</value>
      <webElementGuid>7c9d1583-f523-4c44-a429-7d7ef1c65517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='numberOfPackages']</value>
      <webElementGuid>84959e9c-0137-4610-904b-5ccffe4fb807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>e83db5a5-5b87-45c4-9234-236694bad88e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '1' and @name = 'numberOfPackages' and @type = 'number']</value>
      <webElementGuid>cbf7e339-17be-4d7a-9292-40bb68fbfc56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
