<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UNID_unidSerNum</name>
   <tag></tag>
   <elementGuidId>9002b584-fe85-4fe6-a176-8dd535419756</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#unidSerNum</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='unidSerNum']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bfffc9b-8cd3-4dba-9cfa-ee46fa22a0b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1b3b4c59-41ee-4ac1-8536-0b906732c78c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>unidSerNum</value>
      <webElementGuid>438cf088-4078-4345-b41f-b8296db66b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>unidSerNum</value>
      <webElementGuid>209479d2-f44b-4ac2-ad30-184a159b1488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9134f7b0-b284-4317-b2cf-ca9793704b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>3485b7b5-b378-4dee-a363-4a8287a9dab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1111</value>
      <webElementGuid>5b4bce06-3354-449c-926f-36cbdb31fa6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f2cdb82b-28f3-448d-a2ac-67cbb31b3ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_w-100__NIwLp theme-module_border-bottom__unqVG theme-module_form-control__0sG2o theme-module_is-invalid__v55iH is-invalid form-control</value>
      <webElementGuid>28d6976f-5c34-4958-97ed-9f4746783e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a9e78171-1585-4349-b3ee-6f8d7d971c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;unidSerNum&quot;)</value>
      <webElementGuid>47e6e4b7-8a76-4c60-95b9-5446151bce42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='unidSerNum']</value>
      <webElementGuid>350aabb9-6fd6-4208-9f40-f959758811aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>d85e918a-db47-4df3-9560-7ba66c849e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'unidSerNum' and @name = 'unidSerNum' and @placeholder = '1111' and @type = 'number']</value>
      <webElementGuid>934545cf-8af7-48d7-ab18-f6a806a1909b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
