<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__goodsDescription</name>
   <tag></tag>
   <elementGuidId>74cb8561-db17-485e-959e-b649554e7f3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#goodsDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='goodsDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44f4c297-25d8-42f8-9fe6-a0de0d226c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fd4eaa2c-12e4-413a-98bd-15cf67c430cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7bc6a7b1-3cda-461d-9d5e-56f55e14d128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f88d05d1-06f0-42cf-8184-f113851348de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>goodsDescription</value>
      <webElementGuid>acf279b0-8008-439d-bd6c-90f66d0c0871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>goodsDescription</value>
      <webElementGuid>0af432b8-463b-44bf-94c1-53e942b52e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>06cb2ac9-46a7-419a-b810-b4959d9be9aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>60e4dd5a-e5fd-46b7-9281-c016a950859b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>ce7e065c-f880-4040-b26e-878a06a1dff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>86450b6d-b6b8-45c4-8a4d-491f70a95d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goodsDescription&quot;)</value>
      <webElementGuid>3b97535c-6532-4ac8-90a7-e4579af80617</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='goodsDescription']</value>
      <webElementGuid>132347eb-5579-4760-b22c-4364bcccb11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div[2]/div/div/div/div[2]/div[6]/input</value>
      <webElementGuid>76e50294-44f9-48a4-9c0b-6a1b09762b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>1df6db18-9c3c-439f-bc79-55b8d8a1a047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'goodsDescription' and @id = 'goodsDescription' and @placeholder = 'Description' and @type = 'text']</value>
      <webElementGuid>038daeca-c39d-4f5b-9530-9bb2a9611f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
