<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TI_transportIndex</name>
   <tag></tag>
   <elementGuidId>0fb62dcc-8371-44eb-b313-16dde1d921bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='transportIndex']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;transportIndex&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83f0d030-e2b7-4f93-8280-94792ed025b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>3b64f3e0-76f8-4849-93e5-ab195021c4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transportIndex</value>
      <webElementGuid>310eac00-fbc6-4324-a131-a6c9c0cde56e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1fd8dd8f-9233-47eb-8df8-54c0894f48c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>267ad3c0-67ed-45db-9aa6-7cb8c5dbb03e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG  form-control</value>
      <webElementGuid>62735a69-e072-49e3-bdfc-24bdfab68697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>778bf2b6-927a-4e05-b9e9-244c49e86da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ccd86ffc-0e83-419f-a160-a1c000cd0836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ccn-CCNWCBCDangerousGoodsDetails-Input d-flex justify-content-between align-items-center&quot;]/div[@class=&quot;ccn-CCNWCBCDangerousGoodsDetails-InputField&quot;]/input[@class=&quot;theme-module_form-control__0sG2o theme-module_border-bottom__unqVG  form-control&quot;]</value>
      <webElementGuid>c9fc4337-8e2f-47e7-ba1a-f6a628e5b218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='transportIndex']</value>
      <webElementGuid>38f4122b-04e5-4fe1-829e-61918e5c9154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>21f34d7e-82a6-4b4f-bf55-4bfa28093f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '1.1' and @name = 'transportIndex' and @type = 'text']</value>
      <webElementGuid>59709cf0-af42-4b31-9a7f-42f0b638350b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
