<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_For insurance purpose_commodityDescription</name>
   <tag></tag>
   <elementGuidId>7adbe8a0-dc81-4515-8dd7-410c82781a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commodityDescription</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='commodityDescription']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b2b5fd7-6006-480c-842a-251e20dfd7d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>340cd727-d1b9-4e0b-9a1d-3546913e5815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commodityDescription</value>
      <webElementGuid>684b713b-3b25-41ce-9a87-282419ec4c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commodityDescription</value>
      <webElementGuid>04ab7957-5a26-4065-ba73-c40cedc273fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cf9dcc61-1e7d-42c4-8a86-c16f081606ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>70571f6f-47a4-4d15-b7a9-f89bc5f1f7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>ec416f27-b272-41aa-a711-a889bea890c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e423bc4b-65cf-432c-8863-500b39a0c0b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG form-control</value>
      <webElementGuid>08b21abc-a074-4df5-aa2e-6f199e83815e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commodityDescription&quot;)</value>
      <webElementGuid>768299eb-1e9b-45c4-bf74-5cf3c9b7e1f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='commodityDescription']</value>
      <webElementGuid>237b7f2b-3320-44f8-9016-994c01b95f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[2]/div/input</value>
      <webElementGuid>7f9bcd21-25ad-488d-a66e-4a05b29ff06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'commodityDescription' and @id = 'commodityDescription' and @placeholder = 'Description' and @type = 'text']</value>
      <webElementGuid>754e531f-fe0f-44b5-aa1d-30a942300553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
