<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ULD Type_uld</name>
   <tag></tag>
   <elementGuidId>f50f5f33-a6d6-4499-b378-acb15fd1fa5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f01ab65f-2ce9-4139-9cf7-9eaa31c10c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ea8176bf-ecdf-49a8-9ca4-bd69202c637a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uld</value>
      <webElementGuid>9b1856a8-fc65-490d-a603-1a77028562d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uld</value>
      <webElementGuid>6c16fc4a-65f8-46ca-ada8-e94e919f959a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c5e15658-c162-4ba5-bf6c-5f9373259f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>83048259-706d-4738-87f4-70140c97cf18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ULD</value>
      <webElementGuid>0ad80af3-e7ec-42f7-aa4b-57888d995aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0930d7b6-9147-477e-bb2f-bc3951c509be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_w-100__NIwLp theme-module_border-bottom__unqVG theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>6137e6b1-8461-4d34-afe9-bc90c0651080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>9a579023-119d-4509-bd66-c81c1c7f75b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uld&quot;)</value>
      <webElementGuid>2fc1a125-fcf9-46ab-a93a-f557bf78e14b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uld']</value>
      <webElementGuid>cf9e2f1e-4284-4401-8f43-fe1328d737f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>eddbe49a-8c25-4318-8708-1dc4eb24abe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uld' and @name = 'uld' and @placeholder = 'ULD' and @type = 'text']</value>
      <webElementGuid>6056d744-5694-4a28-9015-9fd07639af0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
