<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Special Handling Codes_specialHandlin_8a0d5a</name>
   <tag></tag>
   <elementGuidId>84ad05ca-0155-4b88-9775-fec690498890</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#specialHandlingCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='specialHandlingCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd724e1a-9e28-47cf-9765-ee542add53ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d93327b8-711c-4319-8c77-70bc9607353c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>specialHandlingCode</value>
      <webElementGuid>2a259677-1d49-4eac-8953-dfbe91fe93c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>specialHandlingCodes[0].code</value>
      <webElementGuid>e729ca91-34f7-4f84-aa53-208e1ff5ad11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>124cb200-15c8-4948-bf52-43fcfdd77129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4c8163f1-8bd1-486a-bb67-f786711e5879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AAA</value>
      <webElementGuid>82680b43-8879-4a05-8605-5edd3c89a0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>36a6173b-8f11-47e4-94a2-4348676e900f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>8cbc9be9-290d-4fdc-a8db-eb6817926c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4a4ec0d8-3172-4422-9493-67e54167facc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-content&quot;]/form[@class=&quot;booking-form&quot;]/div[@class=&quot;ccn-BC__BookingDetails&quot;]/div[@class=&quot;theme-module_ElevatedPaper__-PaWa theme-module_pb-0__v396a&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;theme-module_card__5p5Cl&quot;]/div[@class=&quot;theme-module_card-body__rJq5X&quot;]/div[@class=&quot;ml-2 theme-module_p-2__Y647L theme-module_pb-2__8fUif row&quot;]/div[@class=&quot;w-7 m-0 px-2.5 py-1 col-sm-1&quot;]/div[@class=&quot;ccn-CCNCommonCodeInputWithDropdown&quot;]/input[@id=&quot;specialHandlingCode&quot;]</value>
      <webElementGuid>7d351e13-4956-48b7-914e-2a2ea2bc1755</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='specialHandlingCode']</value>
      <webElementGuid>b888ab0a-e635-4d8d-ab1d-832b5ffa911e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div[2]/div/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>ea94de16-7c26-4a00-87d7-5602dc939c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>421d5d2b-e098-4c07-9c1b-b15ea091dfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'specialHandlingCode' and @name = 'specialHandlingCodes[0].code' and @placeholder = 'AAA' and @type = 'text']</value>
      <webElementGuid>8482bf91-ed5e-474e-a870-94464487f46f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
