<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PG_packingGroup</name>
   <tag></tag>
   <elementGuidId>83e93743-c84c-4447-b3c3-c290adc06f67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#packingGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='packingGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddfd14dc-f513-4bfc-94cd-b2cda766a3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fcbfa0d9-a9c2-47db-8e51-cd101cfdb2e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>packingGroup</value>
      <webElementGuid>5be76566-0a4f-48c2-b777-9423a19d3b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>packingGroup</value>
      <webElementGuid>6c1856bc-6b13-4bdb-a82e-b2794ea1251f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>dea03c58-9bb5-4c1f-9d1b-393acd3e7580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>682dbb77-80b6-403f-9669-6e72fd938cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Packing Group</value>
      <webElementGuid>301771cc-209e-4a4f-a40c-5cd1ce9b884f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>819dcad8-0e6e-49f9-932a-8a2a5257e2df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_w-100__NIwLp theme-module_border-bottom__unqVG theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>0cefe8e1-a5ae-431b-8b66-a9b1cdb9a844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>50f319aa-bb45-4050-80a4-e23029333944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;packingGroup&quot;)</value>
      <webElementGuid>f630678f-f4a6-494e-ae4d-59c708a2f4b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='packingGroup']</value>
      <webElementGuid>4da3d7be-6470-45ce-aa45-fc512803515d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>04070772-c0ee-40a4-b5e1-a9d9f596aaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'packingGroup' and @name = 'packingGroup' and @placeholder = 'Packing Group' and @type = 'text']</value>
      <webElementGuid>2c198598-2a3f-4a38-9b8a-4524cc999c38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
