<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight Per ULD (kg)_weight</name>
   <tag></tag>
   <elementGuidId>76526096-69f0-47e3-a6f6-b91feed7e962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uld_weight</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uld_weight']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcc28a49-6ef8-484b-b908-d9d700c51282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uld_weight</value>
      <webElementGuid>faf280ec-4596-4025-889a-b3f0602e29b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weight</value>
      <webElementGuid>00b5ffc5-c0b6-42fc-b7c1-ea56ae9af648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>88c6fe1c-985d-488a-8e1d-d21ecb05d577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>05edc6c0-5229-4807-ab4a-115e8b05cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>11111.1</value>
      <webElementGuid>f1593841-4656-4d98-96f5-d2d6853b9dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3e7eebb-3704-4d04-a61e-1dca9d463f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_border-bottom__unqVG undefined form-control</value>
      <webElementGuid>d652c1a1-23b8-483a-ae79-fe28ce744bab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uld_weight&quot;)</value>
      <webElementGuid>80215a14-3f2a-407f-8e0c-ececafa08c57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uld_weight']</value>
      <webElementGuid>99d1741e-5ef4-41a0-9ba3-abfd8971c645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/input</value>
      <webElementGuid>d165f8dd-c519-49a8-801d-cbecd0f12c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uld_weight' and @name = 'weight' and @placeholder = '11111.1' and @type = 'text']</value>
      <webElementGuid>044f2155-e731-435d-ba67-c002b8d9209f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
