<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ULD Type_uld</name>
   <tag></tag>
   <elementGuidId>f50f5f33-a6d6-4499-b378-acb15fd1fa5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uld</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uld']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d02ae04-3656-4ba0-b3aa-4f88b0c3074e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4f3b4688-723f-4edd-8ecc-90b69e3b5df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uld</value>
      <webElementGuid>70d775ef-aac2-4c2a-8d56-e4d285527ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uld</value>
      <webElementGuid>b4d30405-e22f-4392-9673-96f847887ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11437bf7-c196-4d7b-b72a-9cda9c57d332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8fc6909c-a6ff-49b7-a5f9-6ff2d2c9470d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ULD</value>
      <webElementGuid>5c7bcbf2-4c1a-4ed0-ad7d-f2b7369aed79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3ab3b0fb-ee15-4740-801c-04ff0b46eb77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_w-100__NIwLp theme-module_border-bottom__unqVG theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>3e5d0f7b-f124-405c-9c7c-47e7acbbd305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c053d9b1-ac8b-47f5-918f-d1a883ee232c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uld&quot;)</value>
      <webElementGuid>eab16217-1f74-484e-962a-42c973246fa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uld']</value>
      <webElementGuid>322c527c-c196-4e64-bcb8-4628d69a1918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/input</value>
      <webElementGuid>f460348e-3d56-4b9f-b18c-c0043d8715de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'uld' and @name = 'uld' and @placeholder = 'ULD' and @type = 'text']</value>
      <webElementGuid>8b031be7-ebaa-41e5-b00d-83223928ca72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
