<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_address</name>
   <tag></tag>
   <elementGuidId>9ddd7fa5-bac1-44f4-bc7e-7ba30bf44aa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CCNCommonAddressField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CCNCommonAddressField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85ade25f-e83d-4909-9fc8-29b5619fca14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>16f2d227-02b7-4ab8-bd73-d855e2e52c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNCommonAddressField</value>
      <webElementGuid>99b9a48b-a352-41e2-9a91-414c3ab2631f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>3f7f876b-aca2-4766-97a0-743aadb127a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af45682d-a5fe-4919-a2fb-720f4bf87c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>08d7ae73-851c-47b5-8f0e-a8b2c9cd19f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b3bd784c-a2db-4300-acd4-80a958f17266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG form-control</value>
      <webElementGuid>8579a26e-ee58-434b-8350-30c3d312b687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>46e090ff-187c-479b-b946-bf0325f635af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNCommonAddressField&quot;)</value>
      <webElementGuid>cacdb1f8-abc3-422a-b638-fafd5d54d5b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CCNCommonAddressField']</value>
      <webElementGuid>2620141e-f1c3-44f9-836a-bcffc8e7a6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span[2]/input</value>
      <webElementGuid>fcc10fbc-0db0-42b4-a28a-4ff8554ca05e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CCNCommonAddressField' and @name = 'address' and @type = 'text']</value>
      <webElementGuid>40679aa6-5d29-4ae9-8abc-6c38b813585a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
