<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country_country</name>
   <tag></tag>
   <elementGuidId>eab1cf7e-3973-40c4-93ab-c3724f7eb16d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CCNCommonCountryField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CCNCommonCountryField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af70a335-daf7-418a-ab7a-6366dc153e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a7ed7887-e794-4708-b7a5-1e0c58e3361a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNCommonCountryField</value>
      <webElementGuid>065f1925-8ff2-434b-bc4e-a192af9c4b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>8832b12d-2a0d-4c43-9c73-f226a19c7a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>adc716af-e14b-4e2f-b4f9-fc87b7d4fdb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1be0b0e2-fa2c-4a63-8053-cb272328afaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG form-control</value>
      <webElementGuid>62985992-b20e-412e-a89f-db1e04bf6cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee7448b4-6683-4883-bee1-a851bac5f3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNCommonCountryField&quot;)</value>
      <webElementGuid>36bb3d58-b5de-4966-8a41-261da6eb1da8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CCNCommonCountryField']</value>
      <webElementGuid>50224531-9e17-4ff1-9a8a-e21560b86177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/span[2]/input</value>
      <webElementGuid>54431e1a-1dc2-4292-9b19-d36776240c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CCNCommonCountryField' and @name = 'country' and @type = 'text']</value>
      <webElementGuid>5408cd81-84c2-425a-bbf4-84692d985d62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
