<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Country_country_1</name>
   <tag></tag>
   <elementGuidId>bea3d35d-602e-4737-bdf3-9b875d019539</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CCNCommonCountryWithDropdownField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CCNCommonCountryWithDropdownField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01622034-9cba-4156-b522-9879d17b5f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>22d2cca3-c73a-40af-a817-b5d6f6af8c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CCNCommonCountryWithDropdownField</value>
      <webElementGuid>9680aa16-4aa6-4a45-a8eb-7c845fe81cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>country</value>
      <webElementGuid>0431d895-96fc-492e-bd89-6e1613cc7f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>be752f99-21b7-4fce-bc3c-9b70f3cc02e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>3b99c1c2-6fc8-45c8-ad18-79012972a07a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Select Country</value>
      <webElementGuid>2c46d20b-1528-4567-8a8b-123c9ab9e784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bbc76abb-5d93-4dc5-8c63-a0f44cab868d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>cb2b78e3-2b27-4d5b-be9a-097539739c35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>S</value>
      <webElementGuid>c11d172f-6f57-4a50-b34f-952fee4ba2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CCNCommonCountryWithDropdownField&quot;)</value>
      <webElementGuid>f70442cb-16e0-40f0-918c-aea60a142ed5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CCNCommonCountryWithDropdownField']</value>
      <webElementGuid>750ae9ee-61f7-4ae3-af99-2edcb6ca3d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/div[2]/div/input</value>
      <webElementGuid>087891e0-2e0e-419c-9923-1326ebc96dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CCNCommonCountryWithDropdownField' and @name = 'country' and @placeholder = 'Select Country' and @type = 'text']</value>
      <webElementGuid>cc319cf4-308e-4666-83f5-12948726fb6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
