<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__commodityInfo</name>
   <tag></tag>
   <elementGuidId>a3acd798-37a3-4554-b8a1-6183d3e17d3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#commodityInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='commodityInfo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>142106bf-0301-4e61-b6b8-0e06167f040b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>891b4ae1-990f-4fd4-aa19-90e9fb307d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>commodityInfo</value>
      <webElementGuid>71a53270-5765-476a-b520-e0c71caea635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>commodityInfo</value>
      <webElementGuid>cf29cbd5-6cb2-4e9c-9f31-043cfeaa26f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1ab1447d-df63-4a19-97aa-15c6f1382228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>c89ef3a8-6208-4c04-a873-0f4f80fc2cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3b4a27ad-f9f4-4196-abcf-f93a6077b549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>ec902814-d9f7-4961-ba92-a62f3c2940a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>130e39f0-cd85-4d5e-81a1-450290335026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;commodityInfo&quot;)</value>
      <webElementGuid>024a4b6b-fc1d-4595-acad-4387ab3b9da3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='commodityInfo']</value>
      <webElementGuid>a9952284-eee9-432b-83b9-9ceb8e61ce31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/form/div/div/div[2]/div/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>50469670-f21c-4a14-84e2-c380fc534ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>b7920820-9e63-44ac-a831-e65c24c0233d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'commodityInfo' and @name = 'commodityInfo' and @type = 'text']</value>
      <webElementGuid>c56784c5-824c-4a23-9fcb-ee9605a2c775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
