<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Benzaldehyde</name>
   <tag></tag>
   <elementGuidId>7cede3cb-79aa-4dab-870a-df004cfca8e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='[object Object]0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0c385e41-980d-4263-bd60-8f5d8a5e3dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-CCNCommonCodeInputWithDropdown-item</value>
      <webElementGuid>e3c2366e-9901-438a-94a7-5829e4a6a660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>[object Object]0</value>
      <webElementGuid>f7458bbe-687b-4302-b1ee-6fb9cd9841b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Benzaldehyde</value>
      <webElementGuid>8dc4b48e-1367-4141-8ac6-1d06bf66c060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;[object Object]0&quot;)</value>
      <webElementGuid>6a924932-b8fb-4090-8d11-eebb71b8e547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='[object Object]0']</value>
      <webElementGuid>4f673b61-73a9-461d-8ac5-fba7a4c86fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proper Shipping Name'])[1]/following::li[1]</value>
      <webElementGuid>2c998f05-0aa9-4e4d-91d7-cc4c2bf8ecd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UNID'])[2]/following::li[1]</value>
      <webElementGuid>ba122384-1ecf-4b81-9025-d2ec36412544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PG'])[2]/preceding::li[1]</value>
      <webElementGuid>b5a55462-cbc2-48da-8e2e-99088551d1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>72f7633c-49fd-4364-8b84-435571f566ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = '[object Object]0' and (text() = 'Benzaldehyde' or . = 'Benzaldehyde')]</value>
      <webElementGuid>2a5e37fe-8347-445b-abca-b171998594b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
