<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>path</name>
   <tag></tag>
   <elementGuidId>512360c9-638f-4b96-afe8-e70506f4888e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.Toastify__close-button.Toastify__close-button--colored > svg > path</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>path</value>
      <webElementGuid>e076eafb-315b-45f8-9e2b-686422d4afcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
      <webElementGuid>28f00d3a-d323-41ee-b8b8-b54d3fd0dfa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>d</name>
      <type>Main</type>
      <value>M7.71 8.23l3.75 3.75-1.48 1.48-3.75-3.75-3.75 3.75L1 11.98l3.75-3.75L1 4.48 2.48 3l3.75 3.75L9.98 3l1.48 1.48-3.75 3.75z</value>
      <webElementGuid>8a09fbd8-5ddf-4853-9fc0-58a6dce9ce51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3&quot;)/button[@class=&quot;Toastify__close-button Toastify__close-button--colored&quot;]/svg[1]/path[1]</value>
      <webElementGuid>1c8142c7-f6e5-4a50-a4b2-1f3d15d5da29</webElementGuid>
   </webElementProperties>
</WebElementEntity>
