<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_suffix</name>
   <tag></tag>
   <elementGuidId>e31706bd-be1f-45f0-8209-8bb4776809e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='awb-lookup-button']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>c8ea2094-3e88-4062-89e9-1ae2ff020cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-search</value>
      <webElementGuid>c42f9497-f7b3-42eb-98e2-a4c0ccd079d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;awb-lookup-button&quot;)/i[@class=&quot;bx bx-search&quot;]</value>
      <webElementGuid>c9b79af1-ece4-4d8f-852b-9c9ff3f86fb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='awb-lookup-button']/i</value>
      <webElementGuid>0d41e795-6100-4f90-9289-9bc49729ea7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/i</value>
      <webElementGuid>bdac58b8-e790-4928-a696-64267c6bc7b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
