<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MAWBNumber-18</name>
   <tag></tag>
   <elementGuidId>87f52138-7835-425d-b373-f4819c7a8a68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;gridPendingShipments&quot;]/div[2]/table/tbody/tr/td[2]/a[count(. | //*[(text() = '618-63687326' or . = '618-63687326')]) = count(//*[(text() = '618-63687326' or . = '618-63687326')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;gridPendingShipments&quot;]/div[2]/table/tbody/tr/td[2]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>618-63687326</value>
   </webElementProperties>
</WebElementEntity>
