<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>NewAirline_page</name>
   <tag></tag>
   <elementGuidId>c62a52cf-6ef7-4d3c-aab7-84ae77489646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.theme-module_FormHeader__9hG2s.theme-module_text-start__oAiof</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>471fffd4-f969-4497-b61d-4bd56f4b2134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_FormHeader__9hG2s theme-module_text-start__oAiof</value>
      <webElementGuid>b22696a6-e3e0-414d-80d8-c8396a85f15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Airline</value>
      <webElementGuid>24316175-ea14-45ec-9b35-ceed3dbd2ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;theme-module_mx-3__aqwLY row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;theme-module_ElevatedPaper__-PaWa&quot;]/div[@class=&quot;theme-module_FormHeader__9hG2s theme-module_text-start__oAiof&quot;]</value>
      <webElementGuid>efc7015b-0c0e-4170-a9b5-03e7896d20c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div</value>
      <webElementGuid>bc69a0f9-7a24-4d25-9e26-0b906c215a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::div[1]</value>
      <webElementGuid>94e4eb9e-c719-4ff4-8837-1975c50ac6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Airline']/parent::*</value>
      <webElementGuid>a3ecf242-ccff-444a-b857-c19305662292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/div</value>
      <webElementGuid>04472e86-c8cc-41d6-9610-c00388af3001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'New Airline' or . = 'New Airline')]</value>
      <webElementGuid>8cc86af9-5027-47a3-b55c-7847e11bdabf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
