<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipperCityCode_found</name>
   <tag></tag>
   <elementGuidId>ac9ab370-134c-4ecb-bdc7-64a3c4058601</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tbl1&quot;]/tbody/tr[3]/td[2]/table/tbody/tr/td[4]/span/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl1&quot;]/tbody/tr[3]/td[2]/table/tbody/tr/td[4]/span/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
