<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_password</name>
   <tag></tag>
   <elementGuidId>fae1a495-e980-4d2a-be2b-ba745481bc3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-home/main/app-registration/form/div[2]/div[1]/mat-form-field/div/div[2]/div/mat-error/app-error/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-home/main/app-registration/form/div[2]/div[1]/mat-form-field/div/div[2]/div/mat-error/app-error/span</value>
   </webElementProperties>
</WebElementEntity>
