<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Carrier_dropdown</name>
   <tag></tag>
   <elementGuidId>e12b59c7-e68f-4d12-a456-aa069b7521cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[4]/div[2]/div[2]/span/span/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[4]/div[2]/div[2]/span/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
