<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ULD Contour_contour</name>
   <tag></tag>
   <elementGuidId>e76de804-1c43-45e3-afb3-26166a12cbeb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contour']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contour</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96c4e91d-0c07-4e97-923a-da085bc674b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>ULD Contour</value>
      <webElementGuid>d9ee47c9-e685-4e07-974f-dc86017378fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>53f98bb7-e0ed-4de1-920b-f3eb4ef91a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e04ee01b-a5db-4ea7-bc62-ee9617f365d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contour</value>
      <webElementGuid>4acc7139-048e-4809-8c14-060c22476a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contour</value>
      <webElementGuid>5556ede2-dc98-43fb-9ed7-02b1335f3dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>904982cf-b51c-4702-ba52-57d7cb7e519c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11cbde87-6e43-4503-928d-0f1421065e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input ccn-border-bottom-hover-secondary-primary ccn-common-uld-contour form-control</value>
      <webElementGuid>2d29c9c7-e2e5-40b8-b1ee-9587183693a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>aa271d6c-5c90-4d09-abf4-0506e5240411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contour&quot;)</value>
      <webElementGuid>2754fa7a-56e9-4d44-ae26-027bd612d029</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contour']</value>
      <webElementGuid>ba144013-2073-4a9d-9c37-25d46e4d5875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/span/input</value>
      <webElementGuid>b4d6abd8-f2c6-431c-a5f2-87278c2036f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'ULD Contour' and @id = 'contour' and @name = 'contour' and @type = 'text']</value>
      <webElementGuid>a7879022-09e8-4e85-a9e0-a14ff0cbe0dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
