<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_Product</name>
   <tag></tag>
   <elementGuidId>e387745c-60d4-4132-9feb-ebe3701279bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_ctl00_Content_Content_rwdAssignStation_C_gvAssignProductToStation_ctl00_ctl04_chkAssigned']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/form/div[2]/table/tbody/tr[2]/td[2]/div/div[1]/div[2]/div[2]/div[3]/span/div/div[2]/table/tbody/tr/td[1]/span/input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_ctl00_Content_Content_rwdAssignStation_C_gvAssignProductToStation_ctl00_ctl04_chkAssigned</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$Content$Content$rwdAssignStation$C$gvAssignProductToStation$ctl00$ctl04$chkAssigned</value>
   </webElementProperties>
</WebElementEntity>
