<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_SearchAndSort</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>9dd22e49-d13d-4982-ad68-e63ba36132fe</testSuiteGuid>
   <testCaseLink>
      <guid>bf83b2fb-9dee-4791-aae0-3e3353fd9485</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Authentication Login/Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>7c805b05-2cca-456a-b089-8c726269da0e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 2/Login to Booking Concierge/0 Login Success</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2020a495-7060-4f34-b7e9-4f3017b45cf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b99673a-7f6b-4e9b-ae57-42b8ef9938e6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e09a4a8a-3ba7-4a14-b0de-341c80f496fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Sprint 5/Search n Sort/TC_Search and Sort</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7034f8cd-3999-4ee5-bac8-7cf32faf9c55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>48156083-5b31-4191-8a87-13c5ba074718</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
