<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AirportDES_input-found</name>
   <tag></tag>
   <elementGuidId>ef4bc3ce-b1cb-49ab-bc38-14bf6dafd46f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tblCarrier2&quot;]/tbody/tr[2]/td[1]/span/span[1]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tblCarrier2&quot;]/tbody/tr[2]/td[1]/span/span[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
