<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IssuingCarrierCustCodeCollectCity</name>
   <tag></tag>
   <elementGuidId>d0c2bf4a-1e31-4682-a6f7-f3153df6b725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl2&quot;]/tbody/tr[3]/td[1]/table/tbody/tr/td[4]/div[2]/span/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
