<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IssuingCarrierCustCodeCollect</name>
   <tag></tag>
   <elementGuidId>c79d0fa1-fce8-4809-add7-b97cfe23bb0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl2&quot;]/tbody/tr[3]/td[1]/table/tbody/tr/td[2]/span/span/span[1]</value>
   </webElementProperties>
</WebElementEntity>
