<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShipperCountryCode_dropdown</name>
   <tag></tag>
   <elementGuidId>2fa14040-2242-49aa-a409-9354e7f95c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tbl1&quot;]/tbody/tr[3]/td[2]/table/tbody/tr/td[2]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tbl1&quot;]/tbody/tr[3]/td[2]/table/tbody/tr/td[2]/span/span</value>
   </webElementProperties>
</WebElementEntity>
