<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PI_cargoPackingInstruction</name>
   <tag></tag>
   <elementGuidId>56ca7d4a-b3e4-4694-b692-b50e0003cbb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cargoPackingInstruction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cargoPackingInstruction&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e99f1761-bfd0-4c9e-bf61-cff1f4b5d987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Packing Instruction</value>
      <webElementGuid>7c8af089-9254-45b6-b86c-323fb6c7067d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cargoPackingInstruction</value>
      <webElementGuid>cae5a0ab-56fc-42e3-9da0-6961b2262e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e58a41e9-aeba-49eb-8053-b2481195c01f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57e3a154-fc91-4b27-8c0b-b07eb7fcdd59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o theme-module_border-bottom__unqVG  form-control</value>
      <webElementGuid>bc779e82-6f37-4934-ad50-f6b681ee4382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c572b4eb-7bb8-436d-8bc9-45b28ae4087f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;no_padding modal-open&quot;]/div[3]/div[1]/div[@class=&quot;modal fade show&quot;]/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;ccn-CCNWCBCDangerousGoodsDetails-Input d-flex justify-content-between align-items-center&quot;]/div[@class=&quot;ccn-CCNWCBCDangerousGoodsDetails-InputField&quot;]/input[@class=&quot;theme-module_form-control__0sG2o theme-module_border-bottom__unqVG  form-control&quot;]</value>
      <webElementGuid>421972d8-b7d0-460a-a148-decab9d61c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cargoPackingInstruction']</value>
      <webElementGuid>853ee7d9-fe38-4202-809e-7439e7faeeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>702b0894-ed41-421f-93bf-e357fd711ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Packing Instruction' and @name = 'cargoPackingInstruction' and @type = 'text']</value>
      <webElementGuid>b88895cc-aecd-4bf1-9c02-48e7ac97e4b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
