<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>search_flight</name>
   <tag></tag>
   <elementGuidId>fbf64d2e-7428-49cf-8f15-f7583358fb26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ccn-CCNWCBCFlightSection-search']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.bx.bx-search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>fe247ed4-3c22-461c-8992-eef144628588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bx bx-search</value>
      <webElementGuid>c145f839-9293-4491-a73f-6771a4f38fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccn-CCNWCBCFlightSection-search&quot;)/i[@class=&quot;bx bx-search&quot;]</value>
      <webElementGuid>fccea998-01fe-4c52-831f-1cfea03569d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ccn-CCNWCBCFlightSection-search']/i</value>
      <webElementGuid>87d2ff2c-c62e-4b3a-9cd9-042744edad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/i</value>
      <webElementGuid>68f452a9-0e25-4578-ad33-ce312fa65fe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
