<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AWBPrefix_input-found</name>
   <tag></tag>
   <elementGuidId>13ac68a0-1835-4bbc-8292-2b3511e406b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_txtAwbNumberPrefix_wrapper&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_txtAwbNumberPrefix_wrapper&quot;]</value>
   </webElementProperties>
</WebElementEntity>
