<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CarrierCode_input-found</name>
   <tag></tag>
   <elementGuidId>49942835-935e-4998-963e-5d34662fb656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbAirlineID_DropDown&quot;]/div[2]/ul/li/table/tbody/tr/td[1][count(. | //*[(text() = 'SQ' or . = 'SQ')]) = count(//*[(text() = 'SQ' or . = 'SQ')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cbAirlineID_DropDown&quot;]/div[2]/ul/li/table/tbody/tr/td[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SQ</value>
   </webElementProperties>
</WebElementEntity>
