<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vendor Code - found - Copy</name>
   <tag></tag>
   <elementGuidId>42e63427-7027-4151-b6d0-0cfb633f824b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cboVendorCode_DropDown&quot;]/div[2]/ul/li[3]/table/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;ctl00_ctl00_ContentPlaceHolder_SubPageContent_cboVendorCode_DropDown&quot;]/div[2]/ul/li[3]/table/tbody/tr/td[1]</value>
   </webElementProperties>
</WebElementEntity>
