<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__carrierPrefix</name>
   <tag></tag>
   <elementGuidId>7a0330ed-d11f-45ce-8154-46c2219cfb68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#airline-carrierPrefix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='airline-carrierPrefix']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ee5c8c64-1545-4526-8de1-2d7e58e60f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>airline-carrierPrefix</value>
      <webElementGuid>cb771380-9b4a-48e4-9968-c114797a32d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrierPrefix</value>
      <webElementGuid>e7ed2a8f-f42a-4dc1-a442-4942d9f57cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123</value>
      <webElementGuid>1ebed4bf-5aef-4bfc-a16f-2d6c6d913a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>82af869b-5eb6-4d4d-adbc-9d71adf0c23a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>8ff08d30-7e03-4348-a2e4-64eee551a2bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa5df364-56a5-4cf4-8592-52388f7a14f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;airline-carrierPrefix&quot;)</value>
      <webElementGuid>e3e93dec-647a-456d-b127-c36c518b3b5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='airline-carrierPrefix']</value>
      <webElementGuid>ee5bfca1-36a4-426e-9f33-1760dec55553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div[2]/div/input</value>
      <webElementGuid>0d9a364e-2faa-4b40-8aa1-cef3a7f4c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ee668a3a-0e51-42b4-b734-71cd3d183ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'airline-carrierPrefix' and @name = 'carrierPrefix' and @placeholder = '123' and @type = 'text']</value>
      <webElementGuid>16a3212a-3d0b-432d-8d33-06b02ce450c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
