<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__carrierCode</name>
   <tag></tag>
   <elementGuidId>4a08a522-6d03-4d87-b6f7-f5c8b04964b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#airline-carrierCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='airline-carrierCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>315f3078-d25b-437e-b26d-e947024e64ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>airline-carrierCode</value>
      <webElementGuid>683958b1-14c8-42f3-a1b2-2111ba072889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrierCode</value>
      <webElementGuid>72c38207-67b3-4648-967a-f7a2ee4fc904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AA</value>
      <webElementGuid>361497ac-8f71-4a2c-b96b-a76d34a74e36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>953ac554-ffd2-4d94-8d53-b0411570b2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>theme-module_form-control__0sG2o form-control</value>
      <webElementGuid>aca351d5-d0b6-4e8f-aec2-b6e4dc5ade4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>49a4b41c-5a41-4484-8964-ddebf7be2a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;airline-carrierCode&quot;)</value>
      <webElementGuid>15d977ad-5b5d-46e4-8131-6d0d1d282ba7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='airline-carrierCode']</value>
      <webElementGuid>39e2bb78-bb6c-4d9e-bb52-3d9194293f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div/div/input</value>
      <webElementGuid>7e606cc2-8b4b-4b75-83e0-d4380ad24d72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/input</value>
      <webElementGuid>f1f909de-4eb7-4dbf-8843-ab29f877ad87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'airline-carrierCode' and @name = 'carrierCode' and @placeholder = 'AA' and @type = 'text']</value>
      <webElementGuid>3ce277c7-4fa9-4733-b1f9-ab003bec02a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
