<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__station</name>
   <tag></tag>
   <elementGuidId>d4faa80e-1889-4bfe-95db-19e2c0f41b0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='airline-station']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#airline-station</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>983f23fa-bdaf-4723-887c-a4aa6c1c1afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>airline-station</value>
      <webElementGuid>1b2f2412-c81e-4a8f-8ec5-0b88cdaf9de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>station</value>
      <webElementGuid>18837df8-3ca7-448e-afba-2b3ad9407e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>AAA</value>
      <webElementGuid>d032e3b9-e401-47e6-9c72-95b63ffe08d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>793f564c-1b54-4de4-934a-44f0c36c776a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input form-control form-control</value>
      <webElementGuid>b4d9a4fb-318d-4b48-9e3e-a635d7eeb1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef3c1a37-335c-41f7-aef1-7dc96e8eba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;airline-station&quot;)</value>
      <webElementGuid>82d83fe4-9af6-4243-8a77-bcbeb4b8ef4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='airline-station']</value>
      <webElementGuid>35f75279-e9dd-46c1-864a-e439539a8c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BC-create-airline']/div/form/div/div/div/div[3]/div/span/input</value>
      <webElementGuid>6d45c8ed-f712-4f73-a7a5-8b28e27275b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/input</value>
      <webElementGuid>7e182def-ba11-4707-ba06-e86c700f3fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'AAA' and @id = 'airline-station' and @name = 'station' and @type = 'text']</value>
      <webElementGuid>2a49280a-145d-4941-81b4-467e6dbbc859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div[3]/div/input</value>
      <webElementGuid>568e56b5-576f-4e03-9b21-67a678161bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>f1fde425-3783-426d-823c-f96e647a3339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'airline-station' and @name = 'station' and @placeholder = 'AAA' and @type = 'text']</value>
      <webElementGuid>050067d7-f226-46b5-9521-b7b0dbf2f200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
