<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__carrierPrefix</name>
   <tag></tag>
   <elementGuidId>7a0330ed-d11f-45ce-8154-46c2219cfb68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='airline-carrierPrefix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#airline-carrierPrefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab0f4bce-d4e6-4f9e-b1da-3c104b2446bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>airline-carrierPrefix</value>
      <webElementGuid>dae8d54a-e53c-4e4a-ae3a-d160181cba2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>carrierPrefix</value>
      <webElementGuid>2f870cee-13d0-4dc4-ac99-ba17d78a4e27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>123</value>
      <webElementGuid>8636fdde-c741-4345-9776-b41e4c3340a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>235c031b-31e9-4fec-95df-465b8a44711b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ccn-common-input form-control form-control</value>
      <webElementGuid>9cf5f83a-3ccc-4b5f-8d2c-9ce3f9f1a291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>31472930-4cfd-41ce-912b-5a040f897b18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;airline-carrierPrefix&quot;)</value>
      <webElementGuid>e876861d-c10c-4b39-b15c-29569da82ebb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='airline-carrierPrefix']</value>
      <webElementGuid>160c6607-3bc6-465c-9322-ca53ef2b90e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='BC-create-airline']/div/form/div/div/div/div[2]/div/span/input</value>
      <webElementGuid>5636f48c-61f3-4683-b5c1-4601cbf4e68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>4cd93258-cf5f-43a4-8f11-0a17d93264e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = '123' and @id = 'airline-carrierPrefix' and @name = 'carrierPrefix' and @type = 'text']</value>
      <webElementGuid>9947f3c4-a607-4be8-9cef-afbff1d956d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div[2]/div/input</value>
      <webElementGuid>0d9a364e-2faa-4b40-8aa1-cef3a7f4c36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>ee668a3a-0e51-42b4-b734-71cd3d183ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'airline-carrierPrefix' and @name = 'carrierPrefix' and @placeholder = '123' and @type = 'text']</value>
      <webElementGuid>16a3212a-3d0b-432d-8d33-06b02ce450c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
