<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__emails</name>
   <tag></tag>
   <elementGuidId>204e709d-2e86-4d17-8373-87f31c421283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;emails&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='emails']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29088ee9-dc4a-4ff3-887a-a6c519cb6b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test@test.com</value>
      <webElementGuid>cbf4a2cc-484f-42b4-9bcf-a790e243dc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emails</value>
      <webElementGuid>1eef20f1-f136-4a21-9246-d183c59fdd88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2dbbf1c4-cf23-404a-9bce-a2a609a87459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0 form-control</value>
      <webElementGuid>5ced5c5d-9ae1-4158-a007-35440b0f9515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;theme-module_mx-3__aqwLY row&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;theme-module_ElevatedPaper__-PaWa&quot;]/div[@class=&quot;theme-module_mb-3__08fNz theme-module_form-floating__5bNks&quot;]/form[1]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/div[1]/div[@class=&quot;theme-module_form-control__0sG2o theme-module_emailchips-container__3vPw7 undefined&quot;]/input[@class=&quot;border-0 form-control&quot;]</value>
      <webElementGuid>b10ef950-dec6-45fd-bd99-a2cf851bbd01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='emails']</value>
      <webElementGuid>d08a9b4d-f7f6-4212-842b-8a383879983d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div[2]/form/div/div[4]/div/div/input</value>
      <webElementGuid>aa9cad74-8105-4019-852d-664cde97f9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>3da8af16-adf3-4329-98ef-4e36935bda42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'test@test.com' and @name = 'emails' and @type = 'text']</value>
      <webElementGuid>b2c6c566-94f8-40fb-b7c1-cc332b4f4b6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
