<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MAWBNumber-2</name>
   <tag></tag>
   <elementGuidId>6e633230-1357-4c94-9d54-8c73b40689c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;gridPendingShipments&quot;]/div[2]/table/tbody/tr/td[2]/a[count(. | //*[(text() = '618-63687321' or . = '618-63687321')]) = count(//*[(text() = '618-63687321' or . = '618-63687321')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;gridPendingShipments&quot;]/div[2]/table/tbody/tr/td[2]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>618-63687321</value>
   </webElementProperties>
</WebElementEntity>
